name: Run Pytest Manually

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest allure-pytest pytest-xdist
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests with Allure
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          PYTEST_ADDOPTS: "--color=yes"

        run: pytest -v --tb=short --durations=10 --maxfail=5 -n auto --alluredir=allure-results
        continue-on-error: true

      - name: Load Allure history from gh-pages
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-dir

      - name: Build Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Workflow: ${{ github.workflow }}
            Status: ${{ job.status }}
            Actor: ${{ github.actor }}
            Commit: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            Link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            View report: https://github.io{{ github.run_number }}/index.html